name: Publish

on:
  push:
    tags: [0-9]+.[0-9]+.[0-9]+
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install and build
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel twine
        python -m pip install -r requirements.txt
        python setup.py sdist bdist_wheel
    # - name: Upload
    #   run: |
    #     python3 -m twine upload --repository testpypi dist/*
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      # if: startsWith( github.ref, 'refs/tags/')
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Update the wiki
      
